version: "3.9"

services:
  youtube_rss:
    container_name: "youtube_rss"
    image: "youtube_rss"
    build:
      context: .
      # context: https://github.com/martokk/youtube_rss.git#main
      target: production
    restart: unless-stopped
    # depends_on:
    #   - duckdns
    # env_file:
    #   # - /home/ubuntu/volumes/youtube_rss/.env
    #   - ./youtube_rss/.env
    volumes:
      # - /home/ubuntu/volumes/youtube_rss/data:/youtube_rss/data
      - ./youtube_rss:/youtube_rss
    ports:
      - "5000:5000"
