"""
This type stub file was generated by pyright.
"""

'''
    feedgen.util
    ~~~~~~~~~~~~

    This file contains helper functions for the feed generator module.

    :copyright: 2013, Lars Kiesow <lkiesow@uos.de>
    :license: FreeBSD and LGPL, see license.* for more details.
'''
parser = ...
def xml_fromstring(xmlstring):
    ...

def xml_elem(name, parent=..., **kwargs):
    ...

def ensure_format(val, allowed, required, allowed_values=..., defaults=...): # -> list[Unknown]:
    '''Takes a dictionary or a list of dictionaries and check if all keys are in
    the set of allowed keys, if all required keys are present and if the values
    of a specific key are ok.

    :param val:            Dictionaries to check.
    :param allowed:        Set of allowed keys.
    :param required:       Set of required keys.
    :param allowed_values: Dictionary with keys and sets of their allowed
                           values.
    :param defaults:       Dictionary with default values.
    :returns:              List of checked dictionaries.
    '''
    ...

def formatRFC2822(date):
    '''Make sure the locale setting do not interfere with the time format.
    '''
    ...

