import datetime
from pathlib import Path

from dateutil import tz
from feedgen.feed import FeedGenerator
from loguru import logger

from youtube_rss.models.source import Source
from youtube_rss.paths import FEEDS_PATH


class SourceFeedGenerator(FeedGenerator):
    def __init__(self, source: Source):
        """
        Initialize the SourceFeedGenerator object.

        Args:
            source: The source to retrieve data from.
        """
        super().__init__()
        self.load_extension("podcast")
        self.rss_file_path = get_rss_file_path(source_id=source.id)

        self._generate_feed(source=source)

    def _generate_feed(self, source: Source) -> None:
        """
        Generate the feed data.

        Args:
            source: The source to retrieve data from.
        """
        self.title(source.name)
        self.link(href=source.feed_url, rel="self")
        self.id(source.id)
        self.author({"name": source.author})
        self.link(href=source.url, rel="alternate")
        self.logo(source.logo)
        self.subtitle("Generated by YoutubeRSS")
        self.description(source.description)
        self.pubDate(datetime.datetime.now(tz=tz.tzutc()))
        self.podcast.itunes_author(  # type: ignore # pylint: disable=no-member
            itunes_author=source.author
        )
        self.podcast.itunes_image(  # type: ignore # pylint: disable=no-member
            itunes_image=source.logo
        )

        # Generate Feed Posts
        for video in source.videos:

            published_at = self._get_published_date(
                added_at=video.added_at, released_at=video.released_at
            )

            # Set Post
            post = self.add_entry()
            post.author({"name": video.uploader})
            post.id(video.id)
            post.title(video.title)
            post.link(href=video.url)
            post.description(video.description)
            post.enclosure(
                url=video.feed_media_url, length=str(video.media_filesize), type="video/mp4"
            )  # TODO: Handle non-mp4 files as well
            post.published(published_at.replace(tzinfo=tz.tzutc()))
            post.podcast.itunes_duration(  # type: ignore # pylint: disable=no-member
                itunes_duration=video.duration
            )
            post.podcast.itunes_image(  # type: ignore # pylint: disable=no-member
                itunes_image=f"{video.thumbnail}/?=.jpg"
            )  # type: ignore # pylint: disable=no-member

    def _get_published_date(
        self, added_at: datetime.datetime, released_at: datetime.datetime | None
    ) -> datetime.datetime:
        """
        Returns an estimated published date.

        Args:
            added_at: The date the video was added to the database.
            released_at: The date the video was released on YouTube.

        Returns:
            The latest date between `released_at` and `added_at`.
        """
        if not released_at or released_at.date() == added_at.date():
            return added_at
        return released_at

    async def save(self) -> Path:
        """
        Saves a generated feed to file.
        """
        self.rss_file(filename=self.rss_file_path, encoding="UTF-8", pretty=True)
        return self.rss_file_path


# RSS File
def get_rss_file_path(source_id: str) -> Path:
    """
    Returns the file path for a 'source_id' rss file.
    """
    return FEEDS_PATH / f"{source_id}.rss"


async def get_rss_file(source_id: str) -> Path:
    """
    Returns a validated rss file.
    """
    rss_file = get_rss_file_path(source_id=source_id)

    # Validate RSS File exists
    if not rss_file.exists():
        err_msg = f"RSS file ({source_id}.rss) does not exist for ({source_id=})"
        logger.warning(err_msg)
        raise FileNotFoundError(err_msg)
    return rss_file


async def delete_rss_file(source_id: str):
    rss_file = get_rss_file_path(source_id=source_id)
    rss_file.unlink()


async def build_rss_file(source: Source) -> Path:
    """
    Builds a .rss file for source_id, saves it to disk.
    """
    feed = SourceFeedGenerator(source=source)
    rss_file = await feed.save()
    return rss_file
