"""init

Revision ID: 0d7b56ee619f
Revises: 
Create Date: 2023-01-12 23:37:26.039079

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '0d7b56ee619f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_source_id', table_name='source')
    op.drop_table('source')
    op.drop_index('ix_userdb_id', table_name='userdb')
    op.drop_index('ix_userdb_username', table_name='userdb')
    op.drop_table('userdb')
    op.drop_table('video')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('source_id', sa.VARCHAR(), nullable=False),
    sa.Column('handler', sa.VARCHAR(), nullable=False),
    sa.Column('uploader', sa.VARCHAR(), nullable=True),
    sa.Column('uploader_id', sa.VARCHAR(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('duration', sa.INTEGER(), nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(), nullable=True),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('media_url', sa.VARCHAR(), nullable=True),
    sa.Column('feed_media_url', sa.VARCHAR(), nullable=True),
    sa.Column('media_filesize', sa.INTEGER(), nullable=True),
    sa.Column('released_at', sa.DATETIME(), nullable=True),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userdb',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_userdb_username', 'userdb', ['username'], unique=False)
    op.create_index('ix_userdb_id', 'userdb', ['id'], unique=False)
    op.create_table('source',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.Column('logo', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('ordered_by', sa.VARCHAR(), nullable=True),
    sa.Column('feed_url', sa.VARCHAR(), nullable=True),
    sa.Column('extractor', sa.VARCHAR(), nullable=True),
    sa.Column('handler', sa.VARCHAR(), nullable=True),
    sa.Column('added_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['userdb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_source_id', 'source', ['id'], unique=False)
    # ### end Alembic commands ###
