"""
This type stub file was generated by pyright.
"""

from typing import Type
from sqlmodel import SQLModel, Session
from .basecrud import BaseCRUD

class BaseRepository(BaseCRUD):
    """Base class for CRUD Operations"""
    def __init__(self, db: Session, model: Type[SQLModel]) -> None:
        """
        Constructor
        Args:
            db: the database session
            model: the model class that should be manipulated
        """
        ...
    


